# https://www.nuget.org/api/v2/package/HtmlAgilityPack/1.11.39

---
name: Clip Player Actions Release
on:
  push:
    branches:
    - develop
    paths:
    - 'clip-player/**'
  pull_request:
    branches:
    - develop
    paths:
    - 'clip-player/**'
    types:
    - closed
jobs:
  publish:
    # if: github.event.pull_request.merged == true || github.event == 'push'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
        strict: false 
    - name: Download HtmlAgilityPack
      run: |
        mkdir -p ./hap;
        curl -S -X GET https://www.nuget.org/api/v2/package/HtmlAgilityPack/1.11.39 -o ./hap/htmlagilitypack.nuget; 
        unzip ./hap/htmlagilitypack.nuget -d ./hap;
        mkdir -p ./clip-player/3rdparty/;
        mv ./hap/lib/Net45/* ./clip-player/3rdparty/;
        rm -rf ./hap;
    - name: Encode and Package
        # for f in goal/actions/*; do 
        #   f_data=$(cat $f | base64 -w 0);
        #   sed -i "s|\${$f}|$f_data|" goal/actions.json; 
        # done;
        # echo -n -e "\x78\x83\x52\x69" > action.dat;
        # gzip -ck "goal/actions.json" >> action.dat;
        # base64 -w 0 action.dat > goal/goal.action;
      run: |
        zip -x $(tr '\n' ' ' < clip-player/.zipignore) -r clip-player-overlay-${{ steps.semvers.outputs.v_patch }}.zip ./clip-player/**
    - name: Create the Version Tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ github.token }}
        custom_tag: "${{ steps.semvers.outputs.v_patch }}"
        tag_prefix: ''
    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: clip-player-overlay-${{ steps.semvers.outputs.v_patch }}.zip
        name: clip-player-overlay-${{ steps.semvers.outputs.v_patch }}
        tag: ${{ steps.semvers.outputs.v_patch }}
        token: "${{ github.token }}"
    - name: Merge develop -> main
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: develop
        target_branch: main
        github_token: ${{ github.token }}