---
name: Goal Actions Release
on:
  push:
    branches:
    - develop
    paths:
    - 'goal/**'
  pull_request:
    branches:
    - develop
    paths:
    - 'goal/**'
    types:
    - closed
jobs:
  publish:
    # if: github.event.pull_request.merged == true || github.event == 'push'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
        strict: false

    - run: |
        zip -x $(tr '\n' ' ' < goal/.zipignore) -r goal-overlay-${{ steps.semvers.outputs.v_patch }}.zip ./goal/**
    - name: Create the Version Tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ github.token }}
        custom_tag: "${{ steps.semvers.outputs.v_patch }}"
        tag_prefix: ''
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: "${{ github.token }}"
      with:
        tag_name: "${{ steps.semvers.outputs.v_patch }}"
        name: "goal-overlay-${{ steps.semvers.outputs.v_patch }}"
        files: goal-overlay-${{ steps.semvers.outputs.v_patch }}.zip